/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Validar;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOK accident
 */
public class ConsultarPaises extends javax.swing.JFrame {
    
    private int ID;
    
    /**
     * Creates new form ConsultarPaises
     */
    public ConsultarPaises() {
        initComponents();
        initTabla();
        setResizable(false);
        setLocationRelativeTo(null);
        
        Inicio.ponerTema(Inicio.tema, this, null, false);
        
        //Cargar icono
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconoMain.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogModficarPais = new javax.swing.JDialog();
        jlabelNomPais = new javax.swing.JLabel();
        txtNombrePais = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaises = new javax.swing.JTable();
        btnMod = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        JDialogModficarPais.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDialogModficarPais.setTitle("Modificar País");

        jlabelNomPais.setText("Nombre del país:");

        txtNombrePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePaisActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JDialogModficarPaisLayout = new javax.swing.GroupLayout(JDialogModficarPais.getContentPane());
        JDialogModficarPais.getContentPane().setLayout(JDialogModficarPaisLayout);
        JDialogModficarPaisLayout.setHorizontalGroup(
            JDialogModficarPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogModficarPaisLayout.createSequentialGroup()
                .addGroup(JDialogModficarPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialogModficarPaisLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(JDialogModficarPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelNomPais, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JDialogModficarPaisLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnGuardar)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        JDialogModficarPaisLayout.setVerticalGroup(
            JDialogModficarPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogModficarPaisLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlabelNomPais, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(44, 44, 44))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Países");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTablePaises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePaises);

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnEliminar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePaisActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Validar val = new Validar(1);
        String pais = val.Vcadena(txtNombrePais.getText(), txtNombrePais);

        if (val.comprobarCampos()) {
            //Guardar en la base de datos
            boolean ConfirmInsert = Inicio.sente.insertarTabla("update paises set nombre='" + txtNombrePais.getText()
                                + "' where id_paises =" + ID);
            if (ConfirmInsert) {
                this.dispose();
                JDialogModficarPais.setVisible(false);
                JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
            } else {
                JOptionPane.showMessageDialog(this, "Posible error en base de datos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar los campos correctamente");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        this.setEnabled(false);
        try {
            JDialogModficarPais.setResizable(false);
            JDialogModficarPais.setLocationRelativeTo(null);
            JDialogModficarPais.pack();
            JDialogModficarPais.setVisible(true);
            int fila = jTablePaises.getSelectedRow();
            ID = Integer.parseInt((String)jTablePaises.getValueAt(fila, 0));
            txtNombrePais.setText((String) jTablePaises.getValueAt(fila, 1));
        } catch (ArrayIndexOutOfBoundsException e) {
            JDialogModficarPais.setVisible(false);
            this.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento");
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.setEnabled(false);
        try {
            int fila = jTablePaises.getSelectedRow();
            ID = Integer.parseInt((String)jTablePaises.getValueAt(fila, 0));
            if (Inicio.sente.eliminarElemento("delete from paises where id_paises='" + ID + "'")) {
                JOptionPane.showMessageDialog(this, "Elemento eliminado con exito");
            } else {
                this.toFront();
                JOptionPane.showMessageDialog(this, "No puede eliminar este país ya\n que posee una Localidad en este");
                this.setEnabled(true);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JDialogModficarPais.setVisible(false);
            this.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPaises().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialogModficarPais;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaises;
    private javax.swing.JLabel jlabelNomPais;
    private javax.swing.JTextField txtNombrePais;
    // End of variables declaration//GEN-END:variables

    private void initTabla() {
        //-------------------------------------------------------------
        final String TITULOS[] = new String[]{" ", "Países"};
        DefaultTableModel dt = new DefaultTableModel(null, TITULOS);
        ResultSet rs = Inicio.sente.consulta("select * from paises");
        String columnas[] = new String[2];
        //-------------------------------------------------------------
        try {
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    columnas[i] = rs.getString(i + 1);
                }
                dt.addRow(columnas);
            }
            jTablePaises.setModel(dt);
        } catch (SQLException e) {
        }
    }
}
