/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOK accident
 */
public class ConsultarLocalidades extends javax.swing.JFrame {
    private int id, id2;
    
    /**
     * Creates new form ConsultarLocalidades
     */
    public ConsultarLocalidades() {
        initComponents();
        initTabla();
        setLocationRelativeTo(null);
        
        Inicio.ponerTema(Inicio.tema, this, null, false);
        
        //Cargar icono
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconoMain.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDialogModificarLocalidad = new javax.swing.JDialog();
        btnGuardar = new javax.swing.JButton();
        txtLocalidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLocalidades1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnMod1 = new javax.swing.JButton();
        comboNom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnVertabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocalidades = new javax.swing.JTable();
        btnMod = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalidadActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre de la localidad:");

        javax.swing.GroupLayout jDialogModificarLocalidadLayout = new javax.swing.GroupLayout(jDialogModificarLocalidad.getContentPane());
        jDialogModificarLocalidad.getContentPane().setLayout(jDialogModificarLocalidadLayout);
        jDialogModificarLocalidadLayout.setHorizontalGroup(
            jDialogModificarLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModificarLocalidadLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jDialogModificarLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jDialogModificarLocalidadLayout.setVerticalGroup(
            jDialogModificarLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModificarLocalidadLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jDialogModificarLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(btnGuardar)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTableLocalidades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableLocalidades1);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnMod1.setText("Modificar");
        btnMod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMod1ActionPerformed(evt);
            }
        });

        comboNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNomActionPerformed(evt);
            }
        });

        jLabel2.setText("Pais");

        btnVertabla.setText("Ver tabla");
        btnVertabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVertablaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Localidades");

        jTableLocalidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLocalidades);

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMod)
                        .addGap(28, 28, 28)
                        .addComponent(btnEliminar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {  
            boolean ConfirmInsert = Inicio.sente.insertarTabla("update localidades set nombre='" +txtLocalidad.getText()
                                + "' where id_paises =" + id);
            if (ConfirmInsert) {
                this.dispose();
                
                JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
            } else {
                JOptionPane.showMessageDialog(this, "Posible error en base de datos");
            }
    }                                         

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
          this.setEnabled(false);
        try {
            jDialogModificarLocalidad.setResizable(false);
            jDialogModificarLocalidad.setLocationRelativeTo(null);
            jDialogModificarLocalidad.pack();
            jDialogModificarLocalidad.setVisible(true);
            int fila = jTableLocalidades.getSelectedRow();
            id = Integer.parseInt((String)jTableLocalidades.getValueAt(fila, 0));
            txtLocalidad.setText((String)jTableLocalidades.getValueAt(fila, 1));
        } catch (ArrayIndexOutOfBoundsException e) {
            jDialogModificarLocalidad.setVisible(false);
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento");
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         this.setEnabled(false);
        try {
            int fila = jTableLocalidades.getSelectedRow();
            id = Integer.parseInt((String)jTableLocalidades.getValueAt(fila, 0));
            if (Inicio.sente.eliminarElemento("delete from localidades where id_localidad='" + id + "'")) {
                JOptionPane.showMessageDialog(this, "Elemento eliminado con exito");
            } else {
                JOptionPane.showMessageDialog(this, "No puede eliminar este país \nya que posee una Localidad en este");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            jDialogModificarLocalidad.setVisible(false);
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMod1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMod1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNomActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Validar val = new Validar(1);
        String nombreLocalidad = val.Vcadena(txtLocalidad.getText(), txtLocalidad);
            boolean ConfirmInsert = Inicio.sente.insertarTabla("update localidades set nombre='" + nombreLocalidad
                                + "' where id_localidad =" + id);
        if (val.comprobarCampos()) {
            if (ConfirmInsert) {
                this.dispose();
                jDialogModificarLocalidad.setVisible(false);
                JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
            } else {
                JOptionPane.showMessageDialog(this, "Posible error en base de datos");
            }       
        }else {
            JOptionPane.showMessageDialog(this, "Debe ingresar los campos correctamente");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalidadActionPerformed

    private void btnVertablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVertablaActionPerformed
        // TODO add your handling code here:
        new ConsultarLocalidades().setVisible(true);
    }//GEN-LAST:event_btnVertablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarLocalidades().setVisible(true);
            }
        });
    }
    
    private void initTabla() {
        //-------------------------------------------------------------
        final String TITULOS[] = new String[]{" ", "Países"," "};
        DefaultTableModel dt = new DefaultTableModel(null, TITULOS);
        ResultSet rs = Inicio.sente.consulta("select * from localidades");
        String columnas[] = new String[3];
        //-------------------------------------------------------------
        try {
            while (rs.next()) {
                for (int i = 0; i < 3; i++) {
                    columnas[i] = rs.getString(i + 1);
                }
                dt.addRow(columnas);
            }
            jTableLocalidades.setModel(dt);
        } catch (SQLException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnMod1;
    private javax.swing.JButton btnVertabla;
    private javax.swing.JComboBox<String> comboNom;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialogModificarLocalidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLocalidades;
    private javax.swing.JTable jTableLocalidades1;
    private javax.swing.JTextField txtLocalidad;
    // End of variables declaration//GEN-END:variables
 
}
