/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Sentencias;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author GOK accident
 */
public class Inicio extends javax.swing.JFrame {

    public static Sentencias sente;
    public static String tema = "Por defecto";

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        sente = new Sentencias();

        //Cargar icono
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconoMain.png")).getImage());

        //Realizar conexion
        if (sente.conectar()) {
            setTitle("Accidentes geograficos: Conectado");
        } else {
            JOptionPane.showMessageDialog(this, "Error al intentar establecer conexión");
            System.exit(0);
        }

        //Cargar la imagen de fondo
        ImageIcon img = new ImageIcon("src/Imagenes/logo_principal2.png");
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(jLabelFondo.getWidth(),
                jLabelFondo.getHeight(), Image.SCALE_DEFAULT));
        jLabelFondo.setIcon(icono);
        this.repaint();

        this.getContentPane().setBackground(new Color(17, 88, 147));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTema = new javax.swing.ButtonGroup();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCargar = new javax.swing.JMenu();
        JMICargarAccidente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMICargarPais = new javax.swing.JMenuItem();
        JMICargarLocalidades = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        JMIConsultAccidente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JMIConsultPaís = new javax.swing.JMenuItem();
        JMIConsultLocalidades = new javax.swing.JMenuItem();
        jMenuTema = new javax.swing.JMenu();
        JRadioPorDefecto = new javax.swing.JRadioButtonMenuItem();
        JRadioOscuro = new javax.swing.JRadioButtonMenuItem();
        JMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItemManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accidentes geograficos");
        setForeground(new java.awt.Color(153, 204, 255));
        setIconImages(null);

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuCargar.setBackground(new java.awt.Color(65, 60, 60));
        jMenuCargar.setText("Cargar registros");
        jMenuCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JMICargarAccidente.setText("Cargar Accidentes");
        JMICargarAccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICargarAccidenteActionPerformed(evt);
            }
        });
        jMenuCargar.add(JMICargarAccidente);
        jMenuCargar.add(jSeparator1);

        JMICargarPais.setText("Cargar Países");
        JMICargarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICargarPaisActionPerformed(evt);
            }
        });
        jMenuCargar.add(JMICargarPais);

        JMICargarLocalidades.setText("Cargar Localidades");
        JMICargarLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICargarLocalidadesActionPerformed(evt);
            }
        });
        jMenuCargar.add(JMICargarLocalidades);

        jMenuBar1.add(jMenuCargar);

        jMenuConsultar.setText("Consultar registros");

        JMIConsultAccidente.setText("Consultar Accidentes");
        JMIConsultAccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIConsultAccidenteActionPerformed(evt);
            }
        });
        jMenuConsultar.add(JMIConsultAccidente);
        jMenuConsultar.add(jSeparator2);

        JMIConsultPaís.setText("Consultar Paises");
        JMIConsultPaís.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIConsultPaísActionPerformed(evt);
            }
        });
        jMenuConsultar.add(JMIConsultPaís);

        JMIConsultLocalidades.setText("Consultar Localidades");
        JMIConsultLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIConsultLocalidadesActionPerformed(evt);
            }
        });
        jMenuConsultar.add(JMIConsultLocalidades);

        jMenuBar1.add(jMenuConsultar);

        jMenuTema.setText("Tema");

        GrupoTema.add(JRadioPorDefecto);
        JRadioPorDefecto.setSelected(true);
        JRadioPorDefecto.setText("Por defecto");
        JRadioPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioPorDefectoActionPerformed(evt);
            }
        });
        jMenuTema.add(JRadioPorDefecto);

        GrupoTema.add(JRadioOscuro);
        JRadioOscuro.setText("Oscuro");
        JRadioOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioOscuroActionPerformed(evt);
            }
        });
        jMenuTema.add(JRadioOscuro);

        jMenuBar1.add(jMenuTema);

        JMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        JMenuAyuda.add(jMenuItemAcercaDe);

        jMenuItemManual.setText("Manual de usuario");
        jMenuItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManualActionPerformed(evt);
            }
        });
        JMenuAyuda.add(jMenuItemManual);

        jMenuBar1.add(JMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMICargarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICargarPaisActionPerformed
        CargarPaises cp = new CargarPaises();
        cp.setVisible(true);
    }//GEN-LAST:event_JMICargarPaisActionPerformed

    private void JMICargarAccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICargarAccidenteActionPerformed
        NCargarAccidentes ca = new NCargarAccidentes();
        ca.setVisible(true);
    }//GEN-LAST:event_JMICargarAccidenteActionPerformed

    private void JMICargarLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICargarLocalidadesActionPerformed
        CargarLocalidades cl = new CargarLocalidades();
        cl.setVisible(true);
    }//GEN-LAST:event_JMICargarLocalidadesActionPerformed

    private void JMIConsultPaísActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIConsultPaísActionPerformed
        new ConsultarPaises().setVisible(true);
    }//GEN-LAST:event_JMIConsultPaísActionPerformed

    private void JMIConsultLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIConsultLocalidadesActionPerformed
        new ConsultarLocalidades().setVisible(true);
    }//GEN-LAST:event_JMIConsultLocalidadesActionPerformed

    private void JRadioPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioPorDefectoActionPerformed
        if (JRadioPorDefecto.isSelected()) {
            tema = "Por defecto";
            this.getContentPane().setBackground(new Color(17, 88, 147));
        }
    }//GEN-LAST:event_JRadioPorDefectoActionPerformed

    private void JRadioOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioOscuroActionPerformed
        if (JRadioOscuro.isSelected()) {
            tema = "Oscuro";
            this.getContentPane().setBackground(new Color(57, 67, 75));
        }
    }//GEN-LAST:event_JRadioOscuroActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void JMIConsultAccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIConsultAccidenteActionPerformed
        new ConsultarAccidentes().setVisible(true);
    }//GEN-LAST:event_JMIConsultAccidenteActionPerformed

    private void jMenuItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManualActionPerformed
        try {
            File path = new File("src/Imagenes/manual.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemManualActionPerformed

    static void ponerTema(String tema, JFrame contenedor, JLabel[] labels, boolean poseelabal) {
        switch (tema) {
            case "Por defecto":
                contenedor.getContentPane().setBackground(new Color(80, 163, 231));
                if (poseelabal) {
                    for (int i = 0; i < labels.length; i++) {
                        labels[i].setForeground(Color.BLACK);
                    }
                }
                break;
            case "Oscuro":
                contenedor.getContentPane().setBackground(new Color(57, 67, 75));
                if (poseelabal) {
                    for (int i = 0; i < labels.length; i++) {
                        labels[i].setForeground(Color.WHITE);
                    }
                }
                break;
        }
    }

    static void ponerTemaPanel(String tema, JPanel[] contenedor, JLabel[] labels, boolean poseelabal) {
        switch (tema) {
            case "Por defecto":
                for (int i = 0; i < contenedor.length; i++) {
                    contenedor[i].setBackground(new Color(80, 163, 231));
                }
                if (poseelabal) {
                    for (int i = 0; i < labels.length; i++) {
                        labels[i].setForeground(Color.BLACK);
                    }
                }
                break;
            case "Oscuro":
                for (int i = 0; i < contenedor.length; i++) {
                    contenedor[i].setBackground(new Color(57, 67, 75));
                }
                if (poseelabal) {
                    for (int i = 0; i < labels.length; i++) {
                        labels[i].setForeground(Color.WHITE);
                    }
                }
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoTema;
    private javax.swing.JMenuItem JMICargarAccidente;
    private javax.swing.JMenuItem JMICargarLocalidades;
    private javax.swing.JMenuItem JMICargarPais;
    private javax.swing.JMenuItem JMIConsultAccidente;
    private javax.swing.JMenuItem JMIConsultLocalidades;
    private javax.swing.JMenuItem JMIConsultPaís;
    private javax.swing.JMenu JMenuAyuda;
    private javax.swing.JRadioButtonMenuItem JRadioOscuro;
    private javax.swing.JRadioButtonMenuItem JRadioPorDefecto;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCargar;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemManual;
    private javax.swing.JMenu jMenuTema;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
