/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Validar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author omuno
 */
public class NCargarAccidentes extends javax.swing.JFrame {

    /**
     * Creates new form NCargarAccidentes
     */
    public static boolean mod = false;

    public NCargarAccidentes() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(437, 381);
        setTitle("Accidente");

        //Cargar icono
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconoMain.png")).getImage());

        Inicio.ponerTemaPanel(Inicio.tema, new JPanel[]{jPanelRios, jPanelMontanas, jPanelLagos},
                new JLabel[]{jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6,
                    jLabel7, jLabel8, jLabel9, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14,
                    jLabel15, jLabel16, jLabel17}, true);
        //-----------------------------------------------------------------------------------------
        try {
            String sql = "Select * from paises";
            ResultSet rs = Inicio.sente.consulta(sql);

            while (rs.next()) {
                RComboPais.addItem(rs.getString("nombre"));
                LComboPais.addItem(rs.getString("nombre"));
                MComboPais.addItem(rs.getString("nombre"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(NCargarAccidentes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RtxtPosV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RtxtPosiH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RtxtValorTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboNom = new javax.swing.JComboBox<>();
        RbtnMod = new javax.swing.JButton();
        RbtnGra = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        RtxtKm = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        RComboPais = new javax.swing.JComboBox<>();
        jPanelLagos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LtxtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LtxtPosV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LtxtPosH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LtxtValorTipo = new javax.swing.JTextField();
        LbtnGra = new javax.swing.JButton();
        LbtnMod = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        LComboPais = new javax.swing.JComboBox<>();
        jPanelMontanas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        MtxtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MtxtPosV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MtxtPosH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        MtxtValorTipo = new javax.swing.JTextField();
        MbtnMod = new javax.swing.JButton();
        MbtnGra = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        MComboPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jLabel1.setText("Nombre:");

        RtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion verticar:");

        jLabel3.setText("Posicion Horizonta:");

        RtxtPosiH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtPosiHActionPerformed(evt);
            }
        });

        jLabel4.setText("Longitud:");

        RtxtValorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtValorTipoActionPerformed(evt);
            }
        });

        jLabel5.setText("Localidad:");

        ComboNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNomActionPerformed(evt);
            }
        });

        RbtnMod.setText("Registro ríos");
        RbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnModActionPerformed(evt);
            }
        });

        RbtnGra.setText("Grabar");
        RbtnGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnGraActionPerformed(evt);
            }
        });

        jLabel10.setText("Kilometros:");

        RtxtKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtKmActionPerformed(evt);
            }
        });

        jLabel15.setText("Pais: ");

        RComboPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RComboPaisItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelRiosLayout = new javax.swing.GroupLayout(jPanelRios);
        jPanelRios.setLayout(jPanelRiosLayout);
        jPanelRiosLayout.setHorizontalGroup(
            jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRiosLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(RComboPais, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RtxtPosiH, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(RtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRiosLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ComboNom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelRiosLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelRiosLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel10))
                                        .addComponent(RtxtKm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(RtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel15)
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addComponent(RbtnGra)
                        .addGap(18, 18, 18)
                        .addComponent(RbtnMod)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelRiosLayout.setVerticalGroup(
            jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRiosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RtxtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RtxtPosiH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(RComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34))
                    .addComponent(ComboNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnGra)
                    .addComponent(RbtnMod))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Rios", jPanelRios);

        jLabel6.setText("nombre:");

        jLabel7.setText("Posicion Vertical:");

        jLabel8.setText("Posicion Horizontal:");

        LtxtPosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtxtPosHActionPerformed(evt);
            }
        });

        jLabel9.setText("Superficie:");

        LbtnGra.setText("Grabar");
        LbtnGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtnGraActionPerformed(evt);
            }
        });

        LbtnMod.setText("Registro lagos");
        LbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtnModActionPerformed(evt);
            }
        });

        jLabel16.setText("Pais: ");

        LComboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LComboPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLagosLayout = new javax.swing.GroupLayout(jPanelLagos);
        jPanelLagos.setLayout(jPanelLagosLayout);
        jPanelLagosLayout.setHorizontalGroup(
            jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLagosLayout.createSequentialGroup()
                .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLagosLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(LtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLagosLayout.createSequentialGroup()
                                    .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel9))
                                    .addGap(51, 51, 51))
                                .addComponent(LComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LtxtValorTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLagosLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(LbtnGra)
                        .addGap(18, 18, 18)
                        .addComponent(LbtnMod)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelLagosLayout.setVerticalGroup(
            jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLagosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLagosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLagosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbtnGra)
                    .addComponent(LbtnMod))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lagos", jPanelLagos);

        jLabel11.setText("Nombre:");

        jLabel12.setText("Posicion Horizontal:");

        MtxtPosV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtPosVActionPerformed(evt);
            }
        });

        jLabel13.setText("Posicion Vertical:");

        MtxtPosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtPosHActionPerformed(evt);
            }
        });

        jLabel14.setText("Altura:");

        MtxtValorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtValorTipoActionPerformed(evt);
            }
        });

        MbtnMod.setText("Registro Montañas");
        MbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbtnModActionPerformed(evt);
            }
        });

        MbtnGra.setText("Grabar");
        MbtnGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbtnGraActionPerformed(evt);
            }
        });

        jLabel17.setText("Pais: ");

        javax.swing.GroupLayout jPanelMontanasLayout = new javax.swing.GroupLayout(jPanelMontanas);
        jPanelMontanas.setLayout(jPanelMontanasLayout);
        jPanelMontanasLayout.setHorizontalGroup(
            jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontanasLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMontanasLayout.createSequentialGroup()
                        .addComponent(MbtnGra)
                        .addGap(18, 18, 18)
                        .addComponent(MbtnMod))
                    .addGroup(jPanelMontanasLayout.createSequentialGroup()
                        .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MtxtPosV, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MtxtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(MtxtValorTipo)
                            .addComponent(MComboPais, 0, 109, Short.MAX_VALUE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelMontanasLayout.setVerticalGroup(
            jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontanasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MbtnMod)
                    .addComponent(MbtnGra))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Montañas", jPanelMontanas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

//MONTAÑA
    private void MbtnGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbtnGraActionPerformed
        int comprobar = 0;
        Validar val = new Validar(4);
        val.Vcadena(MtxtNombre.getText(), MtxtNombre);
        val.Ventero(MtxtPosV.getText(), MtxtPosV, false);
        val.Ventero(MtxtPosH.getText(), MtxtPosH, false);
        val.Ventero(MtxtValorTipo.getText(), MtxtValorTipo, true);
        if (val.comprobarCampos()) {
            if (mod) {
                String sqlm1 = "Update accidentes set nombre='" + MtxtNombre.getText() + "',posV=" + MtxtPosV.getText() + ",posH=" + MtxtPosH.getText() + " where id_accidentes=" + ConsultarAccidentes.id;
                String sqlm2 = "Update montañas set altura=" + MtxtValorTipo.getText() + " where id_accidentes=" + ConsultarAccidentes.id;

                if (Inicio.sente.ModificarTabla(sqlm1)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                if (Inicio.sente.ModificarTabla(sqlm2)) {
                    comprobar++;
                } else {
                    comprobar--;
                }

                if (comprobar == 2) {
                    JOptionPane.showMessageDialog(this, "Modifcado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
                mod = false;
            } else {
                //Insertar accidentes
                String sql = "Insert into accidentes values(" + null
                + ", '" + MtxtNombre.getText()
                + "', " + MtxtPosV.getText()
                + ", " + MtxtPosH.getText() + ") ";
                if (Inicio.sente.insertarTabla(sql)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                //Insertar Montaña con ID traido desde bs
                try {
                    ResultSet id = Inicio.sente.consulta("Select id_accidentes from accidentes where nombre='" + MtxtNombre.getText() + "'");
                    if (id.next()) {
                        String sqlr = "Insert into montañas values(" + MtxtValorTipo.getText() + "," + id.getString("id_accidentes") + ")";
                        Inicio.sente.insertarTabla(sqlr);
                        //--------------------------------
                        ResultSet id2 = Inicio.sente.consulta("select id_paises from paises where nombre='" + MComboPais.getSelectedItem() + "'");
                        if (id2.next()) {
                            Inicio.sente.insertarTabla("insert into accidentes_paises values("
                                + id.getString("id_accidentes")
                                + ", " + id2.getString("id_paises") + ")");
                        }
                    }
                    comprobar++;
                } catch (SQLException ex) {
                    System.err.println(ex);
                    comprobar--;
                }

                if (comprobar == 2) {
                    JOptionPane.showMessageDialog(this, "Modifcado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
            }
        }
    }//GEN-LAST:event_MbtnGraActionPerformed

    private void MbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbtnModActionPerformed
        new ConsultarAccidentes().setVisible(true);
        ConsultarAccidentes.Montaña.setSelectedIndex(2);
    }//GEN-LAST:event_MbtnModActionPerformed

    private void MtxtValorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtValorTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtValorTipoActionPerformed

    private void MtxtPosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtPosHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtPosHActionPerformed

    private void MtxtPosVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtPosVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtPosVActionPerformed

    private void LComboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LComboPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LComboPaisActionPerformed

    private void LbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtnModActionPerformed
        new ConsultarAccidentes().setVisible(true);
        ConsultarAccidentes.Montaña.setSelectedIndex(1);
    }//GEN-LAST:event_LbtnModActionPerformed

    private void LbtnGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtnGraActionPerformed
        int comprobar = 0;
        Validar val = new Validar(4);
        val.Vcadena(LtxtNombre.getText(), LtxtNombre);
        val.Ventero(LtxtPosV.getText(), LtxtPosV, false);
        val.Ventero(LtxtPosH.getText(), LtxtPosH, false);
        val.Ventero(LtxtValorTipo.getText(), LtxtValorTipo, true);
        if (val.comprobarCampos()) {
            if (mod) {
                String sqlm1 = "Update accidentes set nombre='" + LtxtNombre.getText() + "',posV=" + LtxtPosV.getText() + ",posH=" + LtxtPosH.getText() + " where id_accidentes=" + ConsultarAccidentes.id;
                String sqlm2 = "Update lagos set superficie=" + LtxtValorTipo.getText() + " where id_accidentes=" + ConsultarAccidentes.id;
                if (Inicio.sente.ModificarTabla(sqlm1)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                if (Inicio.sente.ModificarTabla(sqlm2)) {
                    comprobar++;
                } else {
                    comprobar--;
                }

                if (comprobar == 2) {
                    JOptionPane.showMessageDialog(this, "Modifcado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
                mod = false;
            } else {
                //Insertar accidentes
                String sql = "Insert into accidentes values(" + null
                + ", '" + LtxtNombre.getText()
                + "', " + LtxtPosV.getText()
                + ", " + LtxtPosH.getText() + ") ";
                if (Inicio.sente.insertarTabla(sql)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                //Insertar Lagos con ID traido desde bs
                try {
                    ResultSet id = Inicio.sente.consulta("Select id_accidentes from accidentes where nombre='" + LtxtNombre.getText() + "'");
                    if (id.next()) {
                        String sqlr = "Insert into lagos values(" + LtxtValorTipo.getText() + "," + id.getString("id_accidentes") + ")";
                        Inicio.sente.insertarTabla(sqlr);
                        ResultSet id2 = Inicio.sente.consulta("select id_paises from paises where nombre='" + RComboPais.getSelectedItem() + "'");
                        if (id2.next()) {
                            Inicio.sente.insertarTabla("insert into accidentes_paises values("
                                + id.getString("id_accidentes")
                                + ", " + id2.getString("id_paises") + ")");
                        }
                    }
                    comprobar++;
                } catch (SQLException ex) {
                    System.err.println(ex);
                    comprobar--;
                }

                if (comprobar == 2) {
                    JOptionPane.showMessageDialog(this, "Modifcado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe introducir los campos correctamente");
        }
    }//GEN-LAST:event_LbtnGraActionPerformed

    private void LtxtPosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtxtPosHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LtxtPosHActionPerformed

    private void RComboPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RComboPaisItemStateChanged
        ComboNom.removeAllItems();
        try {
            ResultSet id = Inicio.sente.consulta("select id_paises from paises where nombre='" + RComboPais.getSelectedItem() + "'");
            if (id.next()) {
                String sql = "Select * from localidades where id_paises='" + id.getString("id_paises") + "'";
                ResultSet rs = Inicio.sente.consulta(sql);
                while (rs.next()) {
                    ComboNom.addItem(rs.getString("nombre"));
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(NCargarAccidentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RComboPaisItemStateChanged

    private void RtxtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtKmActionPerformed

    }//GEN-LAST:event_RtxtKmActionPerformed

//RIOS
    private void RbtnGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnGraActionPerformed
        int comprobar = 0;
        Validar val = new Validar(5);
        val.Vcadena(RtxtNombre.getText(), RtxtNombre);
        val.Ventero(RtxtPosV.getText(), RtxtPosV, false);
        val.Ventero(RtxtPosiH.getText(), RtxtPosiH, false);
        val.Ventero(RtxtValorTipo.getText(), RtxtValorTipo, true);
        val.Ventero(RtxtKm.getText(), RtxtKm, true);
        if (val.comprobarCampos()) {
            if (mod) {
                String sqlm1 = "Update accidentes set nombre='" + RtxtNombre.getText() + "',posV=" + RtxtPosV.getText() + ",posH=" + RtxtPosiH.getText() + " where id_accidentes=" + ConsultarAccidentes.id;
                String sqlm2 = "Update rios set longitud=" + RtxtValorTipo.getText() + " where id_accidentes=" + ConsultarAccidentes.id;
                String sqlm3;
                try {
                    ResultSet idLocalidad = Inicio.sente.consulta("select id_localidad from rios_localidades where id_accidentes=" + ConsultarAccidentes.id);
                    if (idLocalidad.next()) {
                        sqlm3 = "UPDATE rios_localidades set km=" + RtxtKm.getText()
                        + " WHERE id_accidentes=" + ConsultarAccidentes.id + " AND "
                        + "id_localidad=" + idLocalidad.getString("id_localidad");
                        if (Inicio.sente.ModificarTabla(sqlm3)) {
                            comprobar++;
                        }
                    }
                } catch (SQLException ex) {
                    System.out.println(ex);
                    comprobar--;
                }
                //----------------------------------------------------
                if (Inicio.sente.ModificarTabla(sqlm1)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                if (Inicio.sente.ModificarTabla(sqlm2)) {
                    comprobar++;
                } else {
                    comprobar--;
                }

                if (comprobar == 3) {
                    JOptionPane.showMessageDialog(this, "Modifcado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
                mod = false;
            } else {
                //Insertar accidentes
                String sql = "Insert into accidentes values(" + null
                + ", '" + RtxtNombre.getText()
                + "', " + RtxtPosV.getText()
                //+ "', " + RtxtKm.getText()
                + ", " + RtxtPosiH.getText() + ") ";
                if (Inicio.sente.insertarTabla(sql)) {
                    comprobar++;
                } else {
                    comprobar--;
                }
                //Insertar Rios con ID traido desde bs
                try {
                    comprobar++;
                    ResultSet id = Inicio.sente.consulta("Select id_accidentes from accidentes where nombre='" + RtxtNombre.getText() + "'");
                    if (id.next()) {
                        String sqlr = "Insert into rios values(" + RtxtValorTipo.getText() + "," + id.getString("id_accidentes") + ")";
                        Inicio.sente.insertarTabla(sqlr);
                        ResultSet id2 = Inicio.sente.consulta("Select id_localidad from localidades where nombre='" + ComboNom.getSelectedItem() + "'");
                        if (id2.next()) {
                            String sqlrl = "Insert into rios_localidades values(" + id.getString("id_accidentes") + "," + id2.getString("id_localidad") + "," + RtxtKm.getText() + ")";
                            Inicio.sente.insertarTabla(sqlrl);
                        }
                        //--------------------------------------
                        ResultSet id3 = Inicio.sente.consulta("select id_paises from paises where nombre='" + RComboPais.getSelectedItem() + "'");
                        if (id3.next()) {
                            Inicio.sente.insertarTabla("insert into accidentes_paises values("
                                + id.getString("id_accidentes")
                                + ", " + id3.getString("id_paises") + ")");
                        }
                    }
                } catch (SQLException ex) {
                    System.err.println("Error: " + ex);
                    comprobar--;
                }

                if (comprobar == 2) {
                    JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al insertar el accidente");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos correctamente");
        }
    }//GEN-LAST:event_RbtnGraActionPerformed

    private void RbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnModActionPerformed
        new ConsultarAccidentes().setVisible(true);
        ConsultarAccidentes.Montaña.setSelectedIndex(0);
    }//GEN-LAST:event_RbtnModActionPerformed

    private void ComboNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNomActionPerformed

    private void RtxtValorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtValorTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtxtValorTipoActionPerformed

    private void RtxtPosiHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtPosiHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtxtPosiHActionPerformed

    private void RtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtxtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NCargarAccidentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComboNom;
    public static javax.swing.JComboBox<String> LComboPais;
    private javax.swing.JButton LbtnGra;
    public static javax.swing.JButton LbtnMod;
    public static javax.swing.JTextField LtxtNombre;
    public static javax.swing.JTextField LtxtPosH;
    public static javax.swing.JTextField LtxtPosV;
    public static javax.swing.JTextField LtxtValorTipo;
    public static javax.swing.JComboBox<String> MComboPais;
    private javax.swing.JButton MbtnGra;
    public static javax.swing.JButton MbtnMod;
    public static javax.swing.JTextField MtxtNombre;
    public static javax.swing.JTextField MtxtPosH;
    public static javax.swing.JTextField MtxtPosV;
    public static javax.swing.JTextField MtxtValorTipo;
    public static javax.swing.JComboBox<String> RComboPais;
    private javax.swing.JButton RbtnGra;
    private javax.swing.JButton RbtnMod;
    public static javax.swing.JTextField RtxtKm;
    public static javax.swing.JTextField RtxtNombre;
    public static javax.swing.JTextField RtxtPosV;
    public static javax.swing.JTextField RtxtPosiH;
    public static javax.swing.JTextField RtxtValorTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelLagos;
    private javax.swing.JPanel jPanelMontanas;
    private javax.swing.JPanel jPanelRios;
    public static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
