/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Validar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omuno
 */
public class NCargarAccidentes extends javax.swing.JFrame {

    /**
     * Creates new form NCargarAccidentes
     */
    boolean mod = false;

    public NCargarAccidentes() {
        String eleccion2 = "";
        initComponents();
        try {

            String sql = "Select * from localidades";
            ResultSet rs = Inicio.sente.consulta(sql);

            while (rs.next()) {
                ComboNom.addItem(rs.getString("id_localidad") + " " + rs.getString("nombre") + " ");
                System.out.println(rs.getString("id_localidad") + " " + rs.getString("nombre") + " ");
            }

        } catch (SQLException ex) {
            Logger.getLogger(NCargarAccidentes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanelRios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RtxtPosV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RtxtPosH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RtxtValorTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboNom = new javax.swing.JComboBox<>();
        RbtnMod = new javax.swing.JButton();
        RbtnGra = new javax.swing.JButton();
        JPanelLagos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LtxtPosV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LtxtPosH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LtxtValorTipo = new javax.swing.JTextField();
        LbtnGra = new javax.swing.JButton();
        LbtnMod = new javax.swing.JButton();
        JPanelMontanas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        MtxtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MtxtPosV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MtxtPosH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        MtxtValorTipo = new javax.swing.JTextField();
        MbtnMod = new javax.swing.JButton();
        MbtnGra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        RtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion verticar:");

        jLabel3.setText("Posicion Horizonta:");

        RtxtPosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtxtPosHActionPerformed(evt);
            }
        });

        jLabel4.setText("Longitud:");

        jLabel5.setText("Localidad:");

        ComboNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNomActionPerformed(evt);
            }
        });

        RbtnMod.setText("Modificar");
        RbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnModActionPerformed(evt);
            }
        });

        RbtnGra.setText("Grabar");
        RbtnGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnGraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelRiosLayout = new javax.swing.GroupLayout(JPanelRios);
        JPanelRios.setLayout(JPanelRiosLayout);
        JPanelRiosLayout.setHorizontalGroup(
            JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanelRiosLayout.createSequentialGroup()
                                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                                        .addComponent(RbtnGra)
                                        .addGap(104, 104, 104))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelRiosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RbtnMod)))
                            .addGroup(JPanelRiosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboNom, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        JPanelRiosLayout.setVerticalGroup(
            JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRiosLayout.createSequentialGroup()
                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(29, 29, 29)
                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ComboNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelRiosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(JPanelRiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnMod)
                    .addComponent(RbtnGra))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rios", JPanelRios);

        jLabel6.setText("nombre:");

        jLabel7.setText("Posicion Vertical:");

        jLabel8.setText("Posicion Horizontal:");

        LtxtPosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtxtPosHActionPerformed(evt);
            }
        });

        jLabel9.setText("Superficie:");

        LbtnGra.setText("Grabar");

        LbtnMod.setText("Modificar");
        LbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtnModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLagosLayout = new javax.swing.GroupLayout(JPanelLagos);
        JPanelLagos.setLayout(JPanelLagosLayout);
        JPanelLagosLayout.setHorizontalGroup(
            JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLagosLayout.createSequentialGroup()
                .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLagosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPanelLagosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LtxtPosH))
                            .addGroup(JPanelLagosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LtxtPosV))
                            .addGroup(JPanelLagosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPanelLagosLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(LbtnGra)
                        .addGap(98, 98, 98)
                        .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbtnMod)
                            .addGroup(JPanelLagosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        JPanelLagosLayout.setVerticalGroup(
            JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLagosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLagosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelLagosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(JPanelLagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbtnGra)
                    .addComponent(LbtnMod))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lagos", JPanelLagos);

        jLabel11.setText("Nombre:");

        jLabel12.setText("Posicion Horizontal:");

        MtxtPosV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtPosVActionPerformed(evt);
            }
        });

        jLabel13.setText("Posicion Vertical:");

        MtxtPosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtPosHActionPerformed(evt);
            }
        });

        jLabel14.setText("Altura:");

        MtxtValorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtxtValorTipoActionPerformed(evt);
            }
        });

        MbtnMod.setText("Modificar");

        MbtnGra.setText("Grabar");
        MbtnGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbtnGraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelMontanasLayout = new javax.swing.GroupLayout(JPanelMontanas);
        JPanelMontanas.setLayout(JPanelMontanasLayout);
        JPanelMontanasLayout.setHorizontalGroup(
            JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelMontanasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPanelMontanasLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(MbtnGra)
                        .addGap(81, 81, 81)
                        .addComponent(MbtnMod)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        JPanelMontanasLayout.setVerticalGroup(
            JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMontanasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(MtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(MtxtValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(MtxtPosV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MtxtPosH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JPanelMontanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MbtnMod)
                    .addComponent(MbtnGra))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Montañas", JPanelMontanas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtxtNombreActionPerformed

    private void LtxtPosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtxtPosHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LtxtPosHActionPerformed

    private void MtxtPosVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtPosVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtPosVActionPerformed

    private void MtxtPosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtPosHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtPosHActionPerformed

    private void MtxtValorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtxtValorTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MtxtValorTipoActionPerformed

    private void RtxtPosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtxtPosHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtxtPosHActionPerformed

    private void RbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnModActionPerformed

    private void MbtnGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbtnGraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MbtnGraActionPerformed

    private void LbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtnModActionPerformed

    }//GEN-LAST:event_LbtnModActionPerformed

    private void ComboNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNomActionPerformed

    private void RbtnGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnGraActionPerformed
        Validar val = new Validar(4);
        val.Vcadena(RtxtNombre.getText(), RtxtNombre);
        val.Ventero(RtxtPosV.getText(), RtxtPosV, false);
        val.Ventero(RtxtPosH.getText(), RtxtPosH, false);
        val.Ventero(RtxtValorTipo.getText(), RtxtValorTipo, true);
        if (mod) {
            String sql = "Update localidad set nombre='" + RtxtNombre.getText() + "', id_paises=" + ComboNom.getSelectedItem().toString().substring(0, 1) + " where id_accidentes=" + null;

            if (Inicio.sente.ModificarTabla("")) {
                System.out.println("modificado con exito");
            } else {
                System.out.println("error.no modifico");
            }
        } else {
            if (val.comprobarCampos()) {
                //Insertar accidentes
                String sql = "Insert into accidentes values(" + null
                        + ", '" + RtxtNombre.getText()
                        + "', " + RtxtPosV.getText()
                        + ", " + RtxtPosH.getText() + ") ";
                System.out.println(sql);
                if (Inicio.sente.insertarTabla(sql)) {
                    JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
                }
                //Insertar Rios con ID traido desde bs
                //Insertar en Rios_localidades
                try {
                    ResultSet id = Inicio.sente.consulta("Select id_accidentes from accidentes where nombre='" + RtxtNombre.getText() + "'");
                    if (id.next()) {
                        
                    }
                } catch (SQLException ex) {
                    System.err.println("Error: " + ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe rellenar los campos satisfactoriamente");
            }
        }


    }//GEN-LAST:event_RbtnGraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NCargarAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NCargarAccidentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboNom;
    private javax.swing.JPanel JPanelLagos;
    private javax.swing.JPanel JPanelMontanas;
    private javax.swing.JPanel JPanelRios;
    private javax.swing.JButton LbtnGra;
    private javax.swing.JButton LbtnMod;
    private javax.swing.JTextField LtxtPosH;
    private javax.swing.JTextField LtxtPosV;
    private javax.swing.JTextField LtxtValorTipo;
    private javax.swing.JButton MbtnGra;
    private javax.swing.JButton MbtnMod;
    private javax.swing.JTextField MtxtNombre;
    private javax.swing.JTextField MtxtPosH;
    private javax.swing.JTextField MtxtPosV;
    private javax.swing.JTextField MtxtValorTipo;
    private javax.swing.JButton RbtnGra;
    private javax.swing.JButton RbtnMod;
    private javax.swing.JTextField RtxtNombre;
    private javax.swing.JTextField RtxtPosH;
    private javax.swing.JTextField RtxtPosV;
    private javax.swing.JTextField RtxtValorTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
